### ISSUE TITLE
Japanese blogspot.jp article causes issue.

### ISSUE THREAD

**Issue by crscheid** [crscheid/php-article-extractor#3]
http://futurememes.blogspot.jp/2017/01/cognitive-easing-human-identity-crisis.html?m=1

Issue appears to be related to character encoding conversion in the goose-php library. We should first see if:

- Is the issue replicable in our test environment
- If so, is it solved by upgrading goose-php
- If not, what is the cause and can we recommend a solution to the goose peeps

```
[2017-03-07 06:15:57] production.ERROR: exception 'ErrorException' with message 'mb_convert_encoding(): Illegal character encoding specified' in /var/www/laravel/vendor/scotteh/php-dom-wrapper/src/Document.php:102
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mb_convert_enco...', '/var/www/larave...', 102, Array)
#1 /var/www/laravel/vendor/scotteh/php-dom-wrapper/src/Document.php(102): mb_convert_encoding('<!DOCTYPE html>...', 'UTF-8', 'UTF-8'')
#2 /var/www/laravel/vendor/scotteh/php-dom-wrapper/src/Traits/ManipulationTrait.php(680): DOMWrap\Document->setHtml('<!DOCTYPE html>...')
#3 /var/www/laravel/vendor/scotteh/php-goose/src/Crawler.php(95): DOMWrap\Document->html('<!DOCTYPE html>...')
#4 /var/www/laravel/vendor/scotteh/php-goose/src/Crawler.php(50): Goose\Crawler->getDocument('<!DOCTYPE html>...')
#5 /var/www/laravel/vendor/scotteh/php-goose/src/Client.php(42): Goose\Crawler->crawl('http://futureme...', NULL)
#6 /var/www/laravel/vendor/crscheid/php-article-extractor/src/ArticleExtractor.php(51): Goose\Client->extractContent('http://futureme...')
#7 /var/www/laravel/app/Http/Controllers/AppController.php(360): Cscheide\ArticleExtractor\ArticleExtractor->getArticleText('http://futureme...')
#8 [internal function]: App\Http\Controllers\AppController->submit(Object(Illuminate\Http\Request))
#9 /var/www/laravel/bootstrap/cache/compiled.php(9424): call_user_func_array(Array, Array)
#10 /var/www/laravel/bootstrap/cache/compiled.php(9486): Illuminate\Routing\Controller->callAction('submit', Array)
#11 /var/www/laravel/bootstrap/cache/compiled.php(9466): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\AppController), Object(Illuminate\Routing\Route), 'submit')
#12 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

```

**Comment by crscheid** [comment]
Not going to fix. Tracked down issue to php-dom-wrapper and posted issue to author here:

https://github.com/scotteh/php-dom-wrapper/issues/4
